### ISSUE TITLE
Numbers are ignored in search

### ISSUE THREAD

**Issue by ilyabirman** [parpalak/rose#15]
When there are pages named “Something 1”, “Something 2”, “Something N”, the search “Something X” does not find a corresponding page, because the number gets filtered out.

**Comment by parpalak** [comment]
Fixed in https://github.com/parpalak/rose/releases/tag/v0.2.3. However, snippets highlighting might be differrent from expected one for some search queries. I think it should be fixed in issue #9 if required.
