### ISSUE TITLE
SQL error while indexing

### ISSUE THREAD

**Issue by Pathologic** [parpalak/rose#23]
https://github.com/parpalak/rose/blob/master/src/S2/Rose/Storage/Database/MysqlRepository.php#L109 - execution of this query throws an exception "SQLSTATE[HY093]: Invalid parameter number", because you are using the same parameters both in insert and update parts of the query.

As documentation says:
> You must include a unique parameter marker for each value you wish to pass in to the statement when you call [PDOStatement::execute()](https://www.php.net/manual/en/pdostatement.execute.php). You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on.

**Comment by parpalak** [comment]
Thanks for reporting. I didn't know about this. Looks like I've always used emulation mode.

Also it's interesting that there is no such a problem in PostgreSQL.
