### ISSUE TITLE
Unknown exception with code "22003" occurred while fetching similar items

### ISSUE THREAD

**Issue by Pathologic** [parpalak/rose#26]
```
SQLSTATE[22003]: Numeric value out of range: 1690 DOUBLE value is out of range in 'pow(`community`.`m`.`word_count`,-(0.5))'
```
MySQL 8.0.28

**Comment by parpalak** [comment]
Already fixed in https://github.com/parpalak/rose/commit/5c8179d857f619638de3f68b4c2c1944c09bb549 and released in https://github.com/parpalak/rose/releases/tag/v2.0.1

**Comment by Pathologic** [comment]
It seems that I forgot to recreate index at the production site. Error is gone after reindexing.
