### ISSUE TITLE
Dependencies conflict with Laravel 10

### ISSUE THREAD

**Issue by Pathologic** [parpalak/rose#27]
Problem 1
    - laravel/framework[v10.10.0, ..., 10.x-dev] require monolog/monolog ^3.0 -> satisfiable by monolog/monolog[3.0.0-RC1, ..., 3.x-dev].
    - monolog/monolog[3.0.0-RC1, ..., 3.x-dev] require psr/log ^2.0 || ^3.0 -> satisfiable by psr/log[2.0.0, 3.0.0, 3.x-dev].
    - You can only install one version of a package, so only one of these can be installed: psr/log[1.0.0, ..., 1.1.4, 2.0.0, 3.0.0, 3.x-dev].
    - s2/rose v2.0.1 requires psr/log ^1.1 -> satisfiable by psr/log[1.1.0, ..., 1.1.4].

**Comment by parpalak** [comment]
Done in https://github.com/parpalak/rose/commit/d00e67da26fd04e86a0e5ed1fcd2bf54226e51ad
